type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  bio: String
  profilePictureUrl: String
}

type Book @table {
  title: String!
  author: String!
  isbn: String!
  createdAt: Timestamp!
  coverImageUrl: String
  description: String
  publicationYear: Int
  pageCount: Int
}

type ReadingActivity @table {
  user: User!
  book: Book!
  status: String!
  createdAt: Timestamp!
  startedReadingAt: Timestamp
  finishedReadingAt: Timestamp
}

type Review @table {
  user: User!
  book: Book!
  rating: Int!
  createdAt: Timestamp!
  isPublic: Boolean!
  reviewText: String
  updatedAt: Timestamp
  readingActivity: ReadingActivity
}

type Follow @table(key: ["follower", "followee"]) {
  follower: User!
  followee: User!
  createdAt: Timestamp!
}

type Shelf @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  isPublic: Boolean!
  description: String
}

type ShelfBook @table(key: ["shelf", "book"]) {
  shelf: Shelf!
  book: Book!
  createdAt: Timestamp!
  note: String
}